/*
 * generated by Xtext
 */
package de.goldschmiede.mapdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MapDslRuntimeModule extends de.goldschmiede.mapdsl.AbstractMapDslRuntimeModule {

}
