/*
* generated by Xtext
*/
package de.goldschmiede.bodsl.ui.contentassist;

import de.goldschmiede.bodsl.ui.contentassist.AbstractBusinessObjectDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class BusinessObjectDslProposalProvider extends AbstractBusinessObjectDslProposalProvider {

}
