/*
* generated by Xtext
*/
package de.goldschmiede.bodsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.goldschmiede.bodsl.services.BusinessObjectDslGrammarAccess;

public class BusinessObjectDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private BusinessObjectDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.goldschmiede.bodsl.parser.antlr.internal.InternalBusinessObjectDslParser createParser(XtextTokenStream stream) {
		return new de.goldschmiede.bodsl.parser.antlr.internal.InternalBusinessObjectDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public BusinessObjectDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BusinessObjectDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
