/*
* generated by Xtext
*/
package de.goldschmiede.bodsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class BusinessObjectDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.goldschmiede.bodsl.ui.internal.BusinessObjectDslActivator.getInstance().getInjector("de.goldschmiede.bodsl.BusinessObjectDsl");
	}
	
}
