/*
* generated by Xtext
*/
package de.goldschmiede.mapdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MapDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/goldschmiede/mapdsl/parser/antlr/internal/InternalMapDslParser.tokens");
	}
}
