/*
 * generated by Xtext
 */
package de.goldschmiede.mapdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MapDslUiModule extends de.goldschmiede.mapdsl.ui.AbstractMapDslUiModule {
	public MapDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
