/*
* generated by Xtext
*/
package de.goldschmiede.bodsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class BusinessObjectDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
