/*
* generated by Xtext
*/
package de.goldschmiede.mapdsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MapDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.goldschmiede.mapdsl.ui.internal.MapDslActivator.getInstance().getInjector("de.goldschmiede.mapdsl.MapDsl");
	}
	
}
