/*
* generated by Xtext
*/
package de.goldschmiede.mapdsl.ui.contentassist;

import de.goldschmiede.mapdsl.ui.contentassist.AbstractMapDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MapDslProposalProvider extends AbstractMapDslProposalProvider {

}
