/*
* generated by Xtext
*/
package de.goldschmiede.mapdsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class MapDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
