/*
 * generated by Xtext
 */
package de.goldschmiede.bodsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BusinessObjectDslUiModule extends de.goldschmiede.bodsl.ui.AbstractBusinessObjectDslUiModule {
	public BusinessObjectDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
