/*
 * generated by Xtext
 */
package de.goldschmiede.bodsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BusinessObjectDslRuntimeModule extends de.goldschmiede.bodsl.AbstractBusinessObjectDslRuntimeModule {

}
